### ISSUE TITLE
Please make a new release with new ScalaPB 0.10.x

### ISSUE THREAD

**Issue by sideeffffect** [fiadliel/fs2-grpc#174]
Could you please make a new release of `fs2-grpc`? We would like to use `fs2-grpc` with the newest ScalaPB `0.10.x`, the latest release `0.6.x` contains old ScalaPB `0.9.x`.
Thank you :pray:

**Comment by rossabaker** [comment]
v0.7.0 is syncing to Maven Central now.

**Comment by rossabaker** [comment]
Wait, don't use that one. I got distracted and released from the wrong branch.
