### ISSUE TITLE
Improve API for reporting failed RPC calls

### ISSUE THREAD

**Issue by fiadliel** [fiadliel/fs2-grpc#18]
To fail a response, you can raise a `StatusRuntimeException`, with code like:
```scala
F.raiseError(io.grpc.Status.INVALID_ARGUMENT
  .withDescription("Foo can not be provided with bar")
  .asRuntimeException())
```

This construction is somewhat awkward, we should instead have an API in this library for it.
Assuming that the approach remains to fail the response (or stream) for a non-Ok response, we could have something like `Status.invalidArgument("Foo can not be provided with bar")`, that returns a failed `F` with appropriate exception.

The full list of status codes is: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

**Comment by rossabaker** [comment]
Do we have a good reason to prefer `StatusException` over `StatusRuntimeException` or vice versa?  The only difference is whether it's checked, which isn't going to make much difference for us.  I think the important thing is that our helpers are consistent.

**Comment by rossabaker** [comment]
From the javadoc, "gRPC's stubs favor StatusRuntimeException," so that seems like a good enough tiebreaker to me.

**Comment by fiadliel** [comment]
@gregmflanagan that sounds cool, thanks!

**Comment by ahjohannessen** [comment]
Reopen if this is unsolved and needs attention.

**Comment by otto-dev** [comment]
Came here searching for the right way to raise Status errors. See nothing wrong with the first comment's way which currently works. Eg.
```scala
    F.raiseError(Status.UNAUTHENTICATED.asRuntimeException())
```
 Maybe it could be added to the docs.
