### ISSUE TITLE
specify location of protocol buffer files

### ISSUE THREAD

**Issue by matematyk60** [fiadliel/fs2-grpc#214]
Hello! It's reallly good to see project like this adapting grpc to cats-effect ecosystem. My daily codebase uses a lot of gRPC. My question is wrether is it possible to change default `<project_root>/src/main/protobuf` location? With sbt-protoc it was straightforward since I had to add option 

```
PB.protoSources in Compile := Seq(
    ".." / "protobufs" / "service1",
    ".." / "protobufs" / "service2"
  )
```

Can I achieve this in fs2-grpc? If not, maybe it's good first issue to start contributing to project?

Let me know what you think

**Comment by ahjohannessen** [comment]
You are able to do everything you can in ScalaPB.

**Comment by matematyk60** [comment]
I see now when i experimented with it a little. So what parts is this project missing? Or is it production ready to use as a fs2 wrapper around ScalaPB ?

**Comment by ahjohannessen** [comment]
It is used in production and ready :)

**Comment by matematyk60** [comment]
Ok so thank you for your replies and I'm looking forward to use your library :)
