### ISSUE TITLE
Should Metadata be provided via Kleisli?

### ISSUE THREAD

**Issue by fiadliel** [fiadliel/fs2-grpc#6]
Currently, trait looks like

```scala
trait HelloService[F[_]] {
  def sayHello(request: HelloRequest, metadata: Metadata): F[HelloResponse]
}
```

should there instead be something like this?
```scala
trait HelloService[F[_]] {
  def sayHello(request: HelloRequest): F[HelloResponse]
}

trait MetadataHelloService[F[_]] extends HelloService[Kleisli[F, Metadata, ?]] {
  def sayHello(request: HelloRequest): Kleisli[F, MetadataService, HelloResponse]
}
```

**Comment by ChristopherDavenport** [comment]
I like what exists there but I haven't been using it to catch ergonomics. Describing currying functions as unique feels a bit fishy unless there is a really good reason to.

**Comment by fiadliel** [comment]
I want the client and server trait to be the same, if possible (we are talking about a "stub", after all).

The issue is twofold:
 1. the `Metadata` type is not especially well typed / very generic.
 2. the client API is quite awkward when you don't actually need any metadata, e.g. `new Metadata()` added to all calls.

I am wondering whether providing an `A => Metadata` (on the client), and `Metadata => A` (on the server), and defining the trait in terms of `A`, might be nicer?

**Comment by ahjohannessen** [comment]
Kleisli seems like a nice approach :)

**Comment by rossabaker** [comment]
I'm not following.  Specifically where would this `A` parameter be added?

**Comment by fiadliel** [comment]
Something like this - 
```scala
def stub[F[_]: Effect, A](f: A => Metadata): ServiceFs2Grpc[Kleisli[F, A, ?]] = new ServiceFs2Grpc[Kleisli[F, A, ?]] {
  // method implementations
}
```

Not clear if it's worth the effort.

**Comment by howardjohn** [comment]
> 2. the client API is quite awkward when you don't actually need any metadata, e.g. `new Metadata()` added to all calls.

It seems like this could potentially easily be fixed by having `new Metadata()` as the default value for in the stub rather than explicitly requiring it.

**Comment by enzief** [comment]
Maybe it's worth it not creating new instances `new Metadata()` everywhere.

**Comment by fiadliel** [comment]
I added the `Metadata` parameter to parallel the options available in the underlying `core` library, since I didn't have a clear view at the time on how useful this parameter would be.

As it currently stands, it seems like it's more often avoided than used, so I do think we need a possibility that doesn't include this parameter.

I'm afraid I still haven't worked through situations like authentication headers, which I want to make as easy to work with as possible.
