### ISSUE TITLE
Make Fs2CodeGenerator available in artifact

### ISSUE THREAD

**Issue by OlafurD** [fiadliel/fs2-grpc#67]
I'm using ScalaPB in an environment with no SBT (we're using Pants) using [ScalaPBC](https://github.com/scalapb/ScalaPB/blob/master/docs/src/main/markdown/scalapbc.md) instead of the SBT plugin to generate the proto implementation.

ScalaPBC has the option of specifying a custom code generator (instead of the default `ScalaPbCodeGenerator`). Would it be possible to publish the FS2CodeGenerator in an maven artifact? The ` org.lyranthe.fs2-grpc.java-runtime` package does not seem to have this artifact

**Comment by rossabaker** [comment]
Sorry for the delayed reply.  I just saw this.  It's published in `org.lyranthe.fs2_grpc.java_runtime.sbt_gen` in the `sbt-java-gen`.  I will look into moving it into java-runtime.

**Comment by rossabaker** [comment]
There is currently no dependency between `java-runtime` and `sbt-java-gen`, and I don't know that we'd want all the dependencies of the latter in sbt scope.  Maybe a third artifact is the way forward here.

**Comment by ahjohannessen** [comment]
Fixed by https://github.com/fiadliel/fs2-grpc/pull/202
